# Generated by Django 5.2.7 on 2026-01-07 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentMail', models.EmailField(max_length=254, unique=True)),
                ('StudentName', models.CharField(max_length=255)),
                ('Tokens', models.IntegerField(default=0)),
                ('ExpectedPosition', models.CharField(blank=True, default='', max_length=255)),
                ('Designation', models.CharField(blank=True, default='', max_length=255)),
                ('Resume', models.CharField(blank=True, default='', max_length=500)),
                ('OurFeedback', models.CharField(blank=True, default='', max_length=500)),
                ('ImprovementsNeeded', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scores', models.JSONField(blank=True, default=list)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='Student.student')),
            ],
        ),
    ]
